# Generated by Django 3.0.8 on 2020-08-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200826_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('4WD', '4WD'), ('Custom', 'Custom'), ('Toyota', 'Toyota'), ('Sprint', 'Sprint')], default='No Category Assigned', max_length=60, verbose_name='category'),
        ),
    ]
