# Generated by Django 3.0.8 on 2020-08-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vehicle_category',
            field=models.CharField(blank=True, choices=[('4WD', '4WD'), ('Custom', 'Custom'), ('Toyota', 'Toyota'), ('Sprint', 'Sprint')], default='No Category Assigned', max_length=60, verbose_name='vehicle_category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Suspension', 'Suspension'), ('Driveline', 'Driveline'), ('Body', 'Body'), ('Acessories', 'Acessories'), ('Race', 'Race')], default='No Category Assigned', max_length=60, verbose_name='category'),
        ),
    ]
