# Generated by Django 3.0.8 on 2020-08-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='vehicle_category',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_categories', to='projects.Category'),
        ),
    ]
