# Generated by Django 3.0.8 on 2020-09-03 03:38

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200829_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=projects.models.get_deadline),
        ),
        migrations.AddField(
            model_name='project',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
