# Generated by Django 3.0.8 on 2020-10-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200903_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_open',
        ),
    ]
